quizmanager/DjangoApp/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("QuizManager/", include("QuizManager.urls")),
    path("", RedirectView.as_view(url="QuizManager/")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quizmanager/QuizManager/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from . import views

urlpatterns = [
    # Index Page
    path("", views.index, name="index"),
    # End Indexes
    # Start Quizzes
    # List of quizzes
    path("quizzes/", views.QuizListView.as_view(), name="quizzes"),
    # Specific Quiz
    path("quiz/<int:pk>", views.QuizDetailView.as_view(), name="quiz-detail"),
    # Quiz CUD
    # Quiz Create
    path("quizzes/create/", views.QuizCreate.as_view(), name="quiz-create"),
    # Quiz Update
    path(
        "quiz/<int:pk>/update/",
        views.QuizUpdate.as_view(),
        name="quiz-update",
    ),
    # QUiz Delete
    path(
        "quiz/<int:pk>/delete/",
        views.QuizDelete.as_view(),
        name="quiz-delete",
    ),
    # End Quizzes
    # Start Questions
    # List of Questions
    path("questions/", views.QuestionListView.as_view(), name="questions"),
    # Specific Question
    path(
        "question/<int:pk>", views.QuestionDetailView.as_view(), name="question-detail"
    ),
    # Questions CUD
    # Question Create
    path("questions/create/", views.QuestionCreate.as_view(), name="question-create"),
    # Question Update
    path(
        "question/<int:pk>/update/",
        views.QuestionUpdate.as_view(),
        name="question-update",
    ),
    # Question Delete
    path(
        "question/<int:pk>/delete/",
        views.QuestionDelete.as_view(),
        name="question-delete",
    ),
    # End Questions
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

quizmanager/QuizManager/models.py
from django.conf import settings
from django.db import models

# Create your models here.
from django.urls import reverse


class Quiz(models.Model):
    """
    A model representing a list of QuizManager in a quiz.
    """

    id = models.AutoField(primary_key=True)
    name = models.CharField(
        max_length=200, help_text="Enter a quiz name", verbose_name="quiz-name"
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name="original_quiz_author",
    )
    updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name="update_quiz_author",
    )
    last_edited = models.DateTimeField(auto_now=True, verbose_name="Last Edited on:")
    questions = models.ManyToManyField(
        "Question", related_name="list_of_questions", blank=True
    )

    class Meta:
        verbose_name = "Quiz"
        verbose_name_plural = "Quizzes"

    def __str__(self):
        """
        String for representing the Model Object.
        :return: self.name
        """
        return self.name

    def get_absolute_url(self):
        return reverse("quiz-detail", args=[str(self.id)])


class Question(models.Model):
    """
    Model representing a question
    """

    id = models.AutoField(primary_key=True)
    question = models.CharField(max_length=200, help_text="Enter your question here.")
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name="original_question_author",
    )
    updated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        related_name="update_question_author",
    )
    last_edited = models.DateTimeField(auto_now=True, verbose_name="Last Edited on:")
    quiz = models.ManyToManyField(Quiz, related_name="in_quizzes", blank=True)

    def __str__(self):
        """
        String for representing the Model Object.
        :return: self.name
        """
        return self.question

    def get_absolute_url(self):
        return reverse("question-detail", args=[str(self.id)])


class Answer(models.Model):
    """Model representing an answer"""

    answer = models.CharField(max_length=200, help_text="Enter your answer here.")
    question = models.ForeignKey(Question, on_delete=models.CASCADE, null=True)
    is_correct = models.BooleanField(help_text="Check if this answer is correct.")
    last_edited = models.DateTimeField(auto_now=True, verbose_name="Last Edited on:")

    def __str__(self):
        """
        String for representing the Model Object.
        :return: self.name
        """
        return self.answer

quizmanager/QuizManager/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.forms.models import inlineformset_factory
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic import CreateView, UpdateView, DeleteView

from .models import Question, Quiz, Answer


@login_required
def index(request) -> render:
    """
    The view function for the home page of the website.
    :param request: the request received
    :return: renders the page index.html
    """

    # How many quizzes and questions are there.
    num_questions = Question.objects.all().count()
    num_quizzes = Quiz.objects.all().count()

    # Number of people who visit the site
    visitors = request.session.get("visitor_count", 1)
    request.session["visitor_count"] = visitors + 1

    # The keys are used in the index.html file.  The template variables there must match the keys here.
    context = {
        "num_questions": num_questions,
        "num_quizzes": num_quizzes,
        "visitor_count": visitors,
    }

    return render(request, "index.html", context=context)


#######


# Quiz views below


#######


class QuizListView(LoginRequiredMixin, generic.ListView):
    model = Quiz
    paginate_by = 10


class QuizDetailView(LoginRequiredMixin, generic.DetailView):
    model = Quiz


class QuizCreate(PermissionRequiredMixin, CreateView):
    permission_required = "QuizManager.add_quiz"

    model = Quiz
    fields = ["name"]
    initial = {"name": "This is a placeholder name.  Replace me."}

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.updated_by = self.request.user
        return super().form_valid(form)


class QuizUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = "QuizManager.change_quiz"

    model = Quiz
    fields = ["name"]

    def form_valid(self, form):
        form.instance.updated_by = self.request.user
        return super().form_valid(form)


class QuizDelete(PermissionRequiredMixin, DeleteView):
    permission_required = "QuizManager.delete_quiz"

    model = Quiz
    success_url = reverse_lazy("quizzes")


#######


# Question Views below


#######


class QuestionListView(LoginRequiredMixin, generic.ListView):
    model = Question
    paginate_by = 10


class QuestionDetailView(LoginRequiredMixin, generic.DetailView):
    model = Question


# Used to add and update answers alongside questions.
AnswerFormset = inlineformset_factory(Question, Answer, fields=("answer", "is_correct"))


class QuestionCreate(PermissionRequiredMixin, CreateView):
    permission_required = "QuizManager.add_question"

    model = Question
    fields = ["question", "quiz"]
    initial = {
        "question": "This is a placeholder question.  Replace me.",
    }

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.object = None

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data["answers"] = AnswerFormset(
                self.request.POST,
            )
        else:
            data["answers"] = AnswerFormset()
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        answers = context["answers"]
        form.instance.author = self.request.user
        form.instance.updated_by = self.request.user
        self.object = form.save()
        if answers.is_valid():
            answers.instance = self.object
            answers.save()
        return super().form_valid(form)


class QuestionUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = "QuizManager.change_question"

    model = Question
    fields = ["question", "quiz"]

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.object = None

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        if self.request.POST:
            data["answers"] = AnswerFormset(
                self.request.POST,
                instance=self.object,
            )
        else:
            data["answers"] = AnswerFormset(
                instance=self.object,
            )
        return data

    def form_valid(self, form):
        context = self.get_context_data()
        answers = context["answers"]
        form.instance.updated_by = self.request.user
        self.object = form.save()
        if answers.is_valid():
            answers.instance = self.object
            answers.save()
        return super().form_valid(form)


class QuestionDelete(PermissionRequiredMixin, DeleteView):
    permission_required = "QuizManager.delete_question"

    model = Question
    success_url = reverse_lazy("questions")


#######


# Answer views below


#######


class AnswerCreate(PermissionRequiredMixin, CreateView):
    permission_required = "QuizManager.add_answer"

    model = Answer
    fields = ["answer", "question", "is_correct"]
    initial = {"answer": "This is a placeholder answer.  Replace me."}

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.updated_by = self.request.user
        return super().form_valid(form)


class AnswerUpdate(PermissionRequiredMixin, UpdateView):
    permission_required = "QuizManager.change_answer"

    model = Answer
    fields = ["answer", "question", "is_correct"]

    def form_valid(self, form):
        form.instance.updated_by = self.request.user
        return super().form_valid(form)


class AnswerDelete(PermissionRequiredMixin, DeleteView):
    permission_required = "QuizManager.delete_answer"

    model = Answer
    success_url = reverse_lazy("answers")

quizmanager/QuizManager/templates/QuizManager/answer_confirm_delete.html
{% extends "base.html" %}

{% block content %}

    <h1>Delete Answer</h1>

    <p>Please confirm you want to delete the following answer: {{ question }}?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Confirm.">
    </form>

{% endblock %}

quizmanager/QuizManager/templates/QuizManager/answer_form.html
{% extends "base.html" %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

quizmanager/QuizManager/templates/QuizManager/question_confirm_delete.html
{% extends "base.html" %}

{% block content %}

    <h1>Delete Question</h1>

    <p>Please confirm you want to delete the following question: {{ question }}?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Confirm.">
    </form>

{% endblock %}

quizmanager/QuizManager/templates/QuizManager/question_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>Question: {{ question.question }}</h1>

    <p><strong>Author:</strong> {{ question.author }} <strong>Last Updated by:</strong> {{ question.updated_by }} </p>
    <p><strong>Last Edited at :</strong> {{ question.last_edited }}</p>
    <h4>In the following quiz(zes):</h4>
    <ol>
        {% for quiz in question.quiz.all %}
            <li>
                <a href="{{ quiz.get_absolute_url }}">{{ quiz.name }}</a>
            </li>
        {% endfor %}
    </ol>

    {% if user.is_authenticated and 'QuizManager.view_answer' in user.get_all_permissions %}
        <h4>Answers:</h4>
        <ol type="A">
            {% for answer in question.answer_set.all %}
                <li>
                    {{ answer.answer }}
                </li>
            {% endfor %}
        </ol>
    {% endif %}
    {% if user.is_authenticated and 'QuizManager.change_question' in user.get_all_permissions %}
        <p>Click <a href="{% url 'question-update' pk=question.id %}"><strong>Here</strong></a> to modify this question
            and its
            answers.</p>
    {% endif %}

    {% if user.is_authenticated and 'QuizManager.delete_question' in user.get_all_permissions %}
        <p>Click <a href="{% url 'question-delete' pk=question.id %}"><strong>Here</strong></a> to delete this question.
    {% endif %}


{% endblock %}

quizmanager/QuizManager/templates/QuizManager/question_form.html
{% extends "base.html" %}

{% block content %}
    <h1>Question Management</h1>
    <h2>You can manage your question here.</h2>
    <p>To change the name, replace the text in the text box below.</p>
    <p>You can assign your question to any quizzes you like. You can use Ctrl+Click to select multiple.</p>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <h2>Your answers are also created here.</h2>
        <p>Please fill the text boxes with your answers, and mark any correct answers.</p>
        <table>
            {{ answers.as_p }}
        </table>
        <p>If you need more answer options, submit the ones you have now and manage the question again. More will have
            been created.</p>
        <p>Any answers left blank will not be shown on other pages.</p>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

quizmanager/QuizManager/templates/QuizManager/question_list.html
{% extends "base.html" %}
{% block content %}
    <h1>Questions List</h1>
    {% if user.is_authenticated and 'QuizManager.add_question' in user.get_all_permissions %}
        <p>Click <a href="{% url 'question-create' %}"><strong>Here</strong></a> to add a new question.</p>
    {% endif %}

    <ol>
        {% for question in question_list %}
            <li>
                <a href="{{ question.get_absolute_url }}">{{ question.question }}</a>
                (Author: {{ question.author }},
                last changed by: {{ question.updated_by }})
            </li>
        {% empty %}
            <p> There are no questions in the manager.</p>
        {% endfor %}
    </ol>
{% endblock %}

quizmanager/QuizManager/templates/QuizManager/quiz_confirm_delete.html
{% extends "base.html" %}

{% block content %}

    <h1>Delete Quiz</h1>

    <p>Please confirm you want to delete the following quiz: {{ question }}?</p>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Confirm.">
    </form>

{% endblock %}

quizmanager/QuizManager/templates/QuizManager/quiz_detail.html
{% extends "base.html" %}

{% block content %}
    <h1>Quiz: {{ quiz.name }}</h1>

    <p><strong>Author:</strong> {{ quiz.author }} <strong>Last Updated by:</strong>{{ quiz.updated_by }}</p>
    <p><strong>Last Edited at:</strong> {{ quiz.last_edited }}</p>
    <h4>Questions:</h4>
    {% if quiz.questions.all %}
        <div style="margin-left:20px;margin-top:20px">
            <ol>
                {% for question in quiz.questions.all %}
                    <li>
                        <a href="{{ question.get_absolute_url }}">{{ question.question }}</a>
                    </li>
                {% endfor %}
            </ol>
        </div>
    {% else %}
        <p>This quiz doesn't have any questions currently.</p>
    {% endif %}
    {% if user.is_authenticated and 'QuizManager.change_question' in user.get_all_permissions %}
        <p>Click <a href="{% url 'quiz-update' pk=quiz.id %}"><strong>Here</strong></a> to modify this quiz.</p>
    {% endif %}

    {% if user.is_authenticated and 'QuizManager.delete_question' in user.get_all_permissions %}
        <p>Click <a href="{% url 'quiz-delete' pk=quiz.id %}"><strong>Here</strong></a> to delete this quiz.
    {% endif %}
{% endblock %}

quizmanager/QuizManager/templates/QuizManager/quiz_form.html
{% extends "base.html" %}
{% block content %}
    <h1>Quiz Management</h1>
    <p>Please change the name of your quiz, and then click Submit.</p>
    <p>To add questions to your quiz, please navigate to the question you wish to add and manage it from there.</p>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
{% endblock %}

quizmanager/QuizManager/templates/QuizManager/quiz_list.html
{% extends "base.html" %}

{% block content %}
    <h1>Quizzes List</h1>
    {% if user.is_authenticated and 'QuizManager.add_quiz' in user.get_all_permissions %}
        <p>Click <a href="{% url 'quiz-create' %}"><strong>Here</strong></a> to add a new quiz.</p>
    {% endif %}
    <ol>
        {% for quiz in quiz_list %}
            <li>
                <a href="{{ quiz.get_absolute_url }}">{{ quiz.name }}</a>
                (Author: {{ quiz.author }},
                last changed by: {{ quiz.updated_by }})
            </li>
        {% empty %}
            <p>There are no quizzes in the manager.</p>
        {% endfor %}
    </ol>
{% endblock %}